version: "3.5"
services:
  mrss-redis:
    container_name: mrss-redis-container
    restart: on-failure:5
    image: redis:alpine
    # Comment below to show redis logs
    # logging:
    #   driver: none
  mrss-ferret-postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:16
    restart: on-failure
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - 'db-data:/var/lib/postgresql/data'
  mrss-ferret:
    image: ghcr.io/ferretdb/ferretdb:2
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://username:password@mrss-ferret-postgres:5432/postgres
      - FERRETDB_AUTH=false
  mrss-bot:
    container_name: mrss-bot-container
    restart: on-failure:3
    # The image can also be used
    # image: synzen/monitorss
    image: puhitaku/monitorss-clone-mrss-bot
    depends_on:
      - mrss-ferret
    environment:
      - DRSS_START=bot
      - DRSS_BOT_TOKEN=
      - DRSS_DATABASE_URI=mongodb://mrss-ferret:27017/rss

volumes:
  db-data:
